import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]
[env]
TERM = "xterm-256color"


[window]
dynamic_padding = true

decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
bold.family = "MesloLGS Nerd Font Mono"
italic.family = "MesloLGS Nerd Font Mono"
bold_italic.family = "MesloLGS Nerd Font Mono"
size = 13
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0
[cursor]
style = "Beam"
blink_interval = 500
thickness = 0.5
